### ISSUE TITLE
Bu versiyondan dolayı di mi ama asıl skati :)))))

### ISSUE THREAD

**Issue by huseyinbarin** [leothecoder/MonoTurkey#1]
Dostum bunun tüm kaynak kodlarını eklesene elinde mevcutsa.

**Comment by leothecoder** [comment]
son kodlarını drive'da paylaşmıştım dostum :+1: bi ara buraya da commitlerim, commitleyince sana haber veririm

**Comment by huseyinbarin** [comment]
doğru unutmuşum yaşlandık artık  biraz folik asit alayım da hafızam güçlensin :((
